services:
  server-database:
    image: postgres:17.1
    container_name: server-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: server
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

  prometheus-performance:
    image: prom/prometheus:v3.2.1
    container_name: prometheus-performance
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=14d
    volumes:
      - ./.docker/prometheus/prometheus-performance.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  prometheus-utilization:
    image: prom/prometheus:v3.2.1
    container_name: prometheus-utilization
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=365d
    volumes:
      - ./.docker/prometheus/prometheus-utilization.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"

  loki:
    image: grafana/loki:3.4.3
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    volumes:
      - ./.docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"


