services:
  server-database:
    image: postgres:17.1
    container_name: server-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: server
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

  prometheus-performance:
    image: prom/prometheus:v3.3.0
    container_name: prometheus-performance
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=14d
    volumes:
      - ./.docker/prometheus/prometheus-performance.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  prometheus-utilization:
    image: prom/prometheus:v3.3.0
    container_name: prometheus-utilization
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=365d
    volumes:
      - ./.docker/prometheus/prometheus-utilization.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"

  promtail:
    image: grafana/promtail:3.4.3
    container_name: promtail
    volumes:
      - ./.logs:/var/log/applications:ro
      - ./.docker/promtail/config.yml:/etc/promtail/config.yml:ro
    command: [ "-config.file=/etc/promtail/config.yml" ]

  loki:
    image: grafana/loki:3.4.3
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    depends_on:
      - promtail

  tempo:
    image: grafana/tempo:2.6.0
    container_name: tempo
    volumes:
      - ./.docker/tempo/config.yaml:/etc/tempo.yaml:ro
      - ./.docker/tempo/data:/tmp/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3110:3100"  # Tempo
      - "9411:9411" # zipkin

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    volumes:
      - ./.docker/alertmanager/config.yaml:/etc/alertmanager/alertmanager.yml
    command: [ "--config.file=/etc/alertmanager/alertmanager.yml" ]
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    volumes:
      - ./.docker/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./.docker/grafana/alertpoints.yml:/etc/grafana/provisioning/alerting/alertpoints.yml:ro
      - ./.docker/grafana/alertrules.yml:/etc/grafana/provisioning/alerting/alertrules.yml:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus-performance
      - prometheus-utilization
      - loki
      - tempo
      - alertmanager

