spring.application.name: sample-server
---
spring:
  sql.init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/server
    username: admin
    password: secret
---
management:
  observations.key-values:
    application: ${spring.application.name}
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  tracing.sampling.probability: 1.0
  metrics.distribution.percentiles-histogram:
    http.server.requests: true
---
logging:
  level:
    org.springframework.data: DEBUG
    de.schaeferd: DEBUG
  file:
    name: .logs/sample-server.log
  structured:
    format:
      file: logstash