spring.application.name: sample-server
---
spring:
  sql.init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/server
    username: admin
    password: secret
---
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  tracing.sampling.probability: 1.0
  metrics.distribution.percentiles-histogram:
    http.server.requests: true