global:
  scrape_interval: 180s
  evaluation_interval: 180s

scrape_configs:
  - job_name: 'sample-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']