apiVersion: 1

contactPoints:
  - orgId: 1
    name: alertmanager
    receivers:
      - uid: alertmanager
        type: prometheus-alertmanager
        disableResolveMessage: false
        settings:
          url: http://alertmanager:9093