apiVersion: 1

datasources:
  - name: prometheus-performance
    uid: prometheus-performance
    type: prometheus
    access: proxy
    url: http://prometheus-performance:9090
    editable: false
    jsonData:
      httpMethod: POST
      #exemplarTraceIdDestinations:
      #  - name: trace_id
      #    datasourceUid: tempo

  - name: prometheus-utilization
    uid: prometheus-utilization
    type: prometheus
    access: proxy
    url: http://prometheus-utilization:9090
    editable: false
    jsonData:
      httpMethod: POST
      #exemplarTraceIdDestinations:
      #  - name: trace_id
      #    datasourceUid: tempo

  - name: loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
    #  derivedFields:
    #    - datasourceUid: tempo
    #      matcherRegex: \[.+,(.+?),
    #      name: TraceID
    #      url: $${__value.raw}