positions:
  filename: /tmp/positions.yaml 

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: sample-server
    static_configs:
      - targets:
          - localhost 
        labels:
          job: sample-server
          application: sample-server
          __path__: /var/log/applications/sample-server.log